comment: false

coverage:
  status:
    project:
      default:
        threshold: 100% # make CI green
    patch:
      default:
        threshold: 100% # make CI green

ignore:
  - '**/tests'
  - '**/benches'
  - '**/examples'
