[package]
name = "serde-bool"
version = "0.1.0"
authors = ["Rob Ede <robjtede@icloud.com>"]
description = "Single-side boolean deserializers."
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
serde = "1"

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
