name: CI

on:
  push:
    branches: [main]
  merge_group:
    types: [checks_requested]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  msrv:
    name: MSRV Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust (MSRV)
        uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
        with:
          toolchain: '1.56'

      - name: Install cargo-hack
        uses: taiki-e/install-action@v2.33.22
        with:
          tool: cargo-hack

      - name: Generate MSRV lockfile
        run: cargo hack --remove-dev-deps generate-lockfile

      - name: Check
        run: cargo check --workspace --all-features

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: actions-rust-lang/setup-rust-toolchain@v1.8.0

      - name: Test
        run: cargo test --workspace --all-features
