name: CI

on:
  push:
    branches: [main]
  merge_group:
    types: [checks_requested]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  read_msrv:
    name: Read MSRV
    uses: actions-rust-lang/msrv/.github/workflows/msrv.yml@v0.1.0

  test:
    needs: read_msrv

    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - { name: msrv, version: '${{ needs.read_msrv.outputs.msrv }}' }
          - { name: stable, version: stable }

    name: Test / ${{ matrix.toolchain.name }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Install Rust (${{ matrix.toolchain.name }})
        uses: actions-rust-lang/setup-rust-toolchain@v1.12.0
        with:
          toolchain: ${{ matrix.toolchain.version }}

      - name: Enter Nix Devshell
        uses: nicknovitski/nix-develop@v1.2.1

      - name: Workaround MSRV issues
        if: matrix.toolchain.name == 'msrv'
        run: just downgrade-for-msrv

      - name: Test
        run: just test
